
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - release
  pull_request:
    branches: 
      - release
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm ci
        npm run build:docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: release
        FOLDER: docs
